name       : aqbanking
version    : 6.0.2
release    : 4
source     :
    - https://www.aquamaniac.de/rdm/attachments/download/243/aqbanking-6.0.2.tar.gz : 1d16f0a16ceb25ec7e8f8cfba6c21f64e18f5e4124f2144957958738fdb08158
license    : GPL-2.0-or-later
component  : programming.library
summary    : AqBanking is a library for online banking and financial applications
description: |
    The intention of AqBanking is to provide a middle layer between the program and the various Online Banking libraries (e.g. AqHBCI, OpenHBCI etc).
builddeps  :
    - pkgconfig(gwenhywfar)
    - pkgconfig(libofx)
    - pkgconfig(xmlsec1-gnutls)
setup      : |
    %configure --with-backends="aqhbci aqofxconnect aqnone"
build      : |
    # Parallel build is buggy
    make
install    : |
    %make_install -j1
