name       : aqbanking
version    : 6.2.5
release    : 7
source     :
    - https://aquamaniac.de/rdm/attachments/download/342/aqbanking-6.2.5.tar.gz : cf5b060e3ec7e3fc925687caf044d4df3dbf9595f23c4fe8ffad78f44af0d6df
license    : GPL-2.0-or-later
component  : programming.library
summary    : AqBanking is a library for online banking and financial applications
description: |
    The intention of AqBanking is to provide a middle layer between the program and the various Online Banking libraries (e.g. AqHBCI, OpenHBCI etc).
builddeps  :
    - pkgconfig(gwenhywfar)
    - pkgconfig(libofx)
    - pkgconfig(xmlsec1-gnutls)
setup      : |
    %configure --with-backends="aqhbci aqofxconnect aqnone"
build      : |
    # Parallel build is buggy
    make
install    : |
    %make_install -j1
