name       : aqbanking
version    : 5.7.8
release    : 2
source     :
    - https://getsol.us/sources/aqbanking-5.7.8.tar.gz : 16f86e4cc49a9eaaa8dfe3206607e627873208bce45a70030c3caea9b5afc768
license    : GPL-2.0-or-later
component  : programming.library
summary    : AqBanking is a library for online banking and financial applications
description: |
    The intention of AqBanking is to provide a middle layer between the program and the various Online Banking libraries (e.g. AqHBCI, OpenHBCI etc).
builddeps  :
    - pkgconfig(gwenhywfar)
    - pkgconfig(libofx)
    - pkgconfig(xmlsec1-gnutls)
setup      : |
    %configure --with-backends="aqhbci aqofxconnect aqnone"
build      : |
    # Parallel build is buggy
    make
install    : |
    %make_install -j1
