name       : aqbanking
version    : 5.8.1
release    : 3
source     :
    - https://www.aquamaniac.de/rdm/attachments/download/105/aqbanking-5.8.1.tar.gz : af063a75ba401de3538f41cca0c7001950086b3e2d4f190ffe3ddfeea1b08454
license    : GPL-2.0-or-later
component  : programming.library
summary    : AqBanking is a library for online banking and financial applications
description: |
    The intention of AqBanking is to provide a middle layer between the program and the various Online Banking libraries (e.g. AqHBCI, OpenHBCI etc).
builddeps  :
    - pkgconfig(gwenhywfar)
    - pkgconfig(libofx)
    - pkgconfig(xmlsec1-gnutls)
setup      : |
    %configure --with-backends="aqhbci aqofxconnect aqnone"
build      : |
    # Parallel build is buggy
    make
install    : |
    %make_install -j1
